// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto/dynamic/dynamic.proto

package dynamic

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DynamicRoutingClient is the client API for DynamicRouting service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DynamicRoutingClient interface {
	RunDynamic(ctx context.Context, in *DynamicRequest, opts ...grpc.CallOption) (*DynamicResponse, error)
}

type dynamicRoutingClient struct {
	cc grpc.ClientConnInterface
}

func NewDynamicRoutingClient(cc grpc.ClientConnInterface) DynamicRoutingClient {
	return &dynamicRoutingClient{cc}
}

func (c *dynamicRoutingClient) RunDynamic(ctx context.Context, in *DynamicRequest, opts ...grpc.CallOption) (*DynamicResponse, error) {
	out := new(DynamicResponse)
	err := c.cc.Invoke(ctx, "/dynamic.DynamicRouting/RunDynamic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DynamicRoutingServer is the server API for DynamicRouting service.
// All implementations must embed UnimplementedDynamicRoutingServer
// for forward compatibility
type DynamicRoutingServer interface {
	RunDynamic(context.Context, *DynamicRequest) (*DynamicResponse, error)
	mustEmbedUnimplementedDynamicRoutingServer()
}

// UnimplementedDynamicRoutingServer must be embedded to have forward compatible implementations.
type UnimplementedDynamicRoutingServer struct {
}

func (UnimplementedDynamicRoutingServer) RunDynamic(context.Context, *DynamicRequest) (*DynamicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunDynamic not implemented")
}
func (UnimplementedDynamicRoutingServer) mustEmbedUnimplementedDynamicRoutingServer() {}

// UnsafeDynamicRoutingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DynamicRoutingServer will
// result in compilation errors.
type UnsafeDynamicRoutingServer interface {
	mustEmbedUnimplementedDynamicRoutingServer()
}

func RegisterDynamicRoutingServer(s grpc.ServiceRegistrar, srv DynamicRoutingServer) {
	s.RegisterService(&DynamicRouting_ServiceDesc, srv)
}

func _DynamicRouting_RunDynamic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DynamicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicRoutingServer).RunDynamic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dynamic.DynamicRouting/RunDynamic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicRoutingServer).RunDynamic(ctx, req.(*DynamicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DynamicRouting_ServiceDesc is the grpc.ServiceDesc for DynamicRouting service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DynamicRouting_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dynamic.DynamicRouting",
	HandlerType: (*DynamicRoutingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunDynamic",
			Handler:    _DynamicRouting_RunDynamic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dynamic/dynamic.proto",
}
