// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/dynamic/dynamic.proto

package dynamic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  float32 `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float32 `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *Location) Reset() {
	*x = Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamic_dynamic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamic_dynamic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_proto_dynamic_dynamic_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type ObjectPaths struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vehicle int32   `protobuf:"varint,1,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	Objects []int32 `protobuf:"varint,2,rep,packed,name=objects,proto3" json:"objects,omitempty"`
}

func (x *ObjectPaths) Reset() {
	*x = ObjectPaths{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamic_dynamic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectPaths) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectPaths) ProtoMessage() {}

func (x *ObjectPaths) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamic_dynamic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectPaths.ProtoReflect.Descriptor instead.
func (*ObjectPaths) Descriptor() ([]byte, []int) {
	return file_proto_dynamic_dynamic_proto_rawDescGZIP(), []int{1}
}

func (x *ObjectPaths) GetVehicle() int32 {
	if x != nil {
		return x.Vehicle
	}
	return 0
}

func (x *ObjectPaths) GetObjects() []int32 {
	if x != nil {
		return x.Objects
	}
	return nil
}

type DynamicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pickup   *Location      `protobuf:"bytes,1,opt,name=pickup,proto3" json:"pickup,omitempty"`
	ObjectId []int32        `protobuf:"varint,2,rep,packed,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Paths    []*ObjectPaths `protobuf:"bytes,3,rep,name=paths,proto3" json:"paths,omitempty"`
}

func (x *DynamicRequest) Reset() {
	*x = DynamicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamic_dynamic_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DynamicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicRequest) ProtoMessage() {}

func (x *DynamicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamic_dynamic_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicRequest.ProtoReflect.Descriptor instead.
func (*DynamicRequest) Descriptor() ([]byte, []int) {
	return file_proto_dynamic_dynamic_proto_rawDescGZIP(), []int{2}
}

func (x *DynamicRequest) GetPickup() *Location {
	if x != nil {
		return x.Pickup
	}
	return nil
}

func (x *DynamicRequest) GetObjectId() []int32 {
	if x != nil {
		return x.ObjectId
	}
	return nil
}

func (x *DynamicRequest) GetPaths() []*ObjectPaths {
	if x != nil {
		return x.Paths
	}
	return nil
}

type DynamicResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vehicle int32   `protobuf:"varint,1,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	Objects []int32 `protobuf:"varint,2,rep,packed,name=objects,proto3" json:"objects,omitempty"`
}

func (x *DynamicResponse) Reset() {
	*x = DynamicResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamic_dynamic_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DynamicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicResponse) ProtoMessage() {}

func (x *DynamicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamic_dynamic_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicResponse.ProtoReflect.Descriptor instead.
func (*DynamicResponse) Descriptor() ([]byte, []int) {
	return file_proto_dynamic_dynamic_proto_rawDescGZIP(), []int{3}
}

func (x *DynamicResponse) GetVehicle() int32 {
	if x != nil {
		return x.Vehicle
	}
	return 0
}

func (x *DynamicResponse) GetObjects() []int32 {
	if x != nil {
		return x.Objects
	}
	return nil
}

var File_proto_dynamic_dynamic_proto protoreflect.FileDescriptor

var file_proto_dynamic_dynamic_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2f,
	0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x64,
	0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x22, 0x44, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x41, 0x0a, 0x0b,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x61, 0x74, 0x68, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65,
	0x68, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x22,
	0x84, 0x01, 0x0a, 0x0e, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x12, 0x1b, 0x0a,
	0x09, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05,
	0x52, 0x08, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x05, 0x70, 0x61,
	0x74, 0x68, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x79, 0x6e, 0x61,
	0x6d, 0x69, 0x63, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x61, 0x74, 0x68, 0x73, 0x52,
	0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x22, 0x45, 0x0a, 0x0f, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69,
	0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x68,
	0x69, 0x63, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x68, 0x69,
	0x63, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x32, 0x53, 0x0a,
	0x0e, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x12,
	0x41, 0x0a, 0x0a, 0x52, 0x75, 0x6e, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x12, 0x17, 0x2e,
	0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63,
	0x2e, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x47, 0x72, 0x6f, 0x77, 0x2d, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x65, 0x2d, 0x4b, 0x47,
	0x50, 0x2f, 0x54, 0x68, 0x6f, 0x74, 0x68, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x79,
	0x6e, 0x61, 0x6d, 0x69, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_dynamic_dynamic_proto_rawDescOnce sync.Once
	file_proto_dynamic_dynamic_proto_rawDescData = file_proto_dynamic_dynamic_proto_rawDesc
)

func file_proto_dynamic_dynamic_proto_rawDescGZIP() []byte {
	file_proto_dynamic_dynamic_proto_rawDescOnce.Do(func() {
		file_proto_dynamic_dynamic_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_dynamic_dynamic_proto_rawDescData)
	})
	return file_proto_dynamic_dynamic_proto_rawDescData
}

var file_proto_dynamic_dynamic_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_dynamic_dynamic_proto_goTypes = []interface{}{
	(*Location)(nil),        // 0: dynamic.Location
	(*ObjectPaths)(nil),     // 1: dynamic.ObjectPaths
	(*DynamicRequest)(nil),  // 2: dynamic.DynamicRequest
	(*DynamicResponse)(nil), // 3: dynamic.DynamicResponse
}
var file_proto_dynamic_dynamic_proto_depIdxs = []int32{
	0, // 0: dynamic.DynamicRequest.pickup:type_name -> dynamic.Location
	1, // 1: dynamic.DynamicRequest.paths:type_name -> dynamic.ObjectPaths
	2, // 2: dynamic.DynamicRouting.RunDynamic:input_type -> dynamic.DynamicRequest
	3, // 3: dynamic.DynamicRouting.RunDynamic:output_type -> dynamic.DynamicResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_dynamic_dynamic_proto_init() }
func file_proto_dynamic_dynamic_proto_init() {
	if File_proto_dynamic_dynamic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_dynamic_dynamic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamic_dynamic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectPaths); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamic_dynamic_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DynamicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamic_dynamic_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DynamicResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_dynamic_dynamic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dynamic_dynamic_proto_goTypes,
		DependencyIndexes: file_proto_dynamic_dynamic_proto_depIdxs,
		MessageInfos:      file_proto_dynamic_dynamic_proto_msgTypes,
	}.Build()
	File_proto_dynamic_dynamic_proto = out.File
	file_proto_dynamic_dynamic_proto_rawDesc = nil
	file_proto_dynamic_dynamic_proto_goTypes = nil
	file_proto_dynamic_dynamic_proto_depIdxs = nil
}
