// message Location{
//     float latitude=1;
//     float longitude=2;
// }

// Dynamic Routing Request
// {
//      path: the path which needs to be added
//      destinations: an array of individual destination locations sorted in ascending order
//                  destination: {
//                                   vehicle_id
//                                }
// }

//Dynamic Routing Response
//{
//  vehicle_id
//  paths: {
//              coordinates
//          }
//}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/dynamic/dynamic.proto

package dynamic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Location) Reset() {
	*x = Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamic_dynamic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamic_dynamic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_proto_dynamic_dynamic_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Location) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Object struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Length     int32     `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	Breadth    int32     `protobuf:"varint,3,opt,name=breadth,proto3" json:"breadth,omitempty"`
	Height     int32     `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	IsDelivery bool      `protobuf:"varint,5,opt,name=is_delivery,json=isDelivery,proto3" json:"is_delivery,omitempty"`
	Location   *Location `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *Object) Reset() {
	*x = Object{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamic_dynamic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamic_dynamic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_proto_dynamic_dynamic_proto_rawDescGZIP(), []int{1}
}

func (x *Object) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Object) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Object) GetBreadth() int32 {
	if x != nil {
		return x.Breadth
	}
	return 0
}

func (x *Object) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Object) GetIsDelivery() bool {
	if x != nil {
		return x.IsDelivery
	}
	return false
}

func (x *Object) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type ObjectPaths struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vehicle int32     `protobuf:"varint,1,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	Objects []*Object `protobuf:"bytes,2,rep,name=objects,proto3" json:"objects,omitempty"`
	Volume  int32     `protobuf:"varint,3,opt,name=volume,proto3" json:"volume,omitempty"`
	Weight  int32     `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`
	Start   *Location `protobuf:"bytes,5,opt,name=start,proto3" json:"start,omitempty"`
}

func (x *ObjectPaths) Reset() {
	*x = ObjectPaths{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamic_dynamic_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectPaths) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectPaths) ProtoMessage() {}

func (x *ObjectPaths) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamic_dynamic_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectPaths.ProtoReflect.Descriptor instead.
func (*ObjectPaths) Descriptor() ([]byte, []int) {
	return file_proto_dynamic_dynamic_proto_rawDescGZIP(), []int{2}
}

func (x *ObjectPaths) GetVehicle() int32 {
	if x != nil {
		return x.Vehicle
	}
	return 0
}

func (x *ObjectPaths) GetObjects() []*Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *ObjectPaths) GetVolume() int32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *ObjectPaths) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ObjectPaths) GetStart() *Location {
	if x != nil {
		return x.Start
	}
	return nil
}

type DynamicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pickup    *Object        `protobuf:"bytes,1,opt,name=pickup,proto3" json:"pickup,omitempty"`
	ObjectIds []int32        `protobuf:"varint,2,rep,packed,name=object_ids,json=objectIds,proto3" json:"object_ids,omitempty"`
	Paths     []*ObjectPaths `protobuf:"bytes,3,rep,name=paths,proto3" json:"paths,omitempty"`
	Hub       *Location      `protobuf:"bytes,4,opt,name=hub,proto3" json:"hub,omitempty"`
}

func (x *DynamicRequest) Reset() {
	*x = DynamicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamic_dynamic_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DynamicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicRequest) ProtoMessage() {}

func (x *DynamicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamic_dynamic_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicRequest.ProtoReflect.Descriptor instead.
func (*DynamicRequest) Descriptor() ([]byte, []int) {
	return file_proto_dynamic_dynamic_proto_rawDescGZIP(), []int{3}
}

func (x *DynamicRequest) GetPickup() *Object {
	if x != nil {
		return x.Pickup
	}
	return nil
}

func (x *DynamicRequest) GetObjectIds() []int32 {
	if x != nil {
		return x.ObjectIds
	}
	return nil
}

func (x *DynamicRequest) GetPaths() []*ObjectPaths {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *DynamicRequest) GetHub() *Location {
	if x != nil {
		return x.Hub
	}
	return nil
}

type DynamicResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vehicle   int32   `protobuf:"varint,1,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	ObjectIds []int32 `protobuf:"varint,2,rep,packed,name=object_ids,json=objectIds,proto3" json:"object_ids,omitempty"`
}

func (x *DynamicResponse) Reset() {
	*x = DynamicResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamic_dynamic_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DynamicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicResponse) ProtoMessage() {}

func (x *DynamicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamic_dynamic_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicResponse.ProtoReflect.Descriptor instead.
func (*DynamicResponse) Descriptor() ([]byte, []int) {
	return file_proto_dynamic_dynamic_proto_rawDescGZIP(), []int{4}
}

func (x *DynamicResponse) GetVehicle() int32 {
	if x != nil {
		return x.Vehicle
	}
	return 0
}

func (x *DynamicResponse) GetObjectIds() []int32 {
	if x != nil {
		return x.ObjectIds
	}
	return nil
}

var File_proto_dynamic_dynamic_proto protoreflect.FileDescriptor

var file_proto_dynamic_dynamic_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2f,
	0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x64,
	0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x22, 0x26, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78,
	0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x22, 0xb2,
	0x01, 0x0a, 0x06, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e,
	0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74,
	0x68, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x72, 0x65, 0x61, 0x64, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x62, 0x72, 0x65, 0x61, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65,
	0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x44, 0x65, 0x6c, 0x69,
	0x76, 0x65, 0x72, 0x79, 0x12, 0x2d, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63,
	0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0xab, 0x01, 0x0a, 0x0b, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x61,
	0x74, 0x68, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x29, 0x0a,
	0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52,
	0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x27, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69,
	0x63, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x22, 0xa9, 0x01, 0x0a, 0x0e, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x06, 0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x06, 0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x12, 0x1d, 0x0a,
	0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x05, 0x52, 0x09, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x73, 0x12, 0x2a, 0x0a, 0x05,
	0x70, 0x61, 0x74, 0x68, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x79,
	0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x61, 0x74, 0x68,
	0x73, 0x52, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x12, 0x23, 0x0a, 0x03, 0x68, 0x75, 0x62, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x68, 0x75, 0x62, 0x22, 0x4a, 0x0a,
	0x0f, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x09,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x73, 0x32, 0x53, 0x0a, 0x0e, 0x44, 0x79, 0x6e,
	0x61, 0x6d, 0x69, 0x63, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x41, 0x0a, 0x0a, 0x52,
	0x75, 0x6e, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x12, 0x17, 0x2e, 0x64, 0x79, 0x6e, 0x61,
	0x6d, 0x69, 0x63, 0x2e, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e, 0x44, 0x79, 0x6e,
	0x61, 0x6d, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x31,
	0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x47, 0x72, 0x6f,
	0x77, 0x2d, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x65, 0x2d, 0x4b, 0x47, 0x50, 0x2f, 0x54, 0x68,
	0x6f, 0x74, 0x68, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_dynamic_dynamic_proto_rawDescOnce sync.Once
	file_proto_dynamic_dynamic_proto_rawDescData = file_proto_dynamic_dynamic_proto_rawDesc
)

func file_proto_dynamic_dynamic_proto_rawDescGZIP() []byte {
	file_proto_dynamic_dynamic_proto_rawDescOnce.Do(func() {
		file_proto_dynamic_dynamic_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_dynamic_dynamic_proto_rawDescData)
	})
	return file_proto_dynamic_dynamic_proto_rawDescData
}

var file_proto_dynamic_dynamic_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_dynamic_dynamic_proto_goTypes = []interface{}{
	(*Location)(nil),        // 0: dynamic.Location
	(*Object)(nil),          // 1: dynamic.Object
	(*ObjectPaths)(nil),     // 2: dynamic.ObjectPaths
	(*DynamicRequest)(nil),  // 3: dynamic.DynamicRequest
	(*DynamicResponse)(nil), // 4: dynamic.DynamicResponse
}
var file_proto_dynamic_dynamic_proto_depIdxs = []int32{
	0, // 0: dynamic.Object.location:type_name -> dynamic.Location
	1, // 1: dynamic.ObjectPaths.objects:type_name -> dynamic.Object
	0, // 2: dynamic.ObjectPaths.start:type_name -> dynamic.Location
	1, // 3: dynamic.DynamicRequest.pickup:type_name -> dynamic.Object
	2, // 4: dynamic.DynamicRequest.paths:type_name -> dynamic.ObjectPaths
	0, // 5: dynamic.DynamicRequest.hub:type_name -> dynamic.Location
	3, // 6: dynamic.DynamicRouting.RunDynamic:input_type -> dynamic.DynamicRequest
	4, // 7: dynamic.DynamicRouting.RunDynamic:output_type -> dynamic.DynamicResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_dynamic_dynamic_proto_init() }
func file_proto_dynamic_dynamic_proto_init() {
	if File_proto_dynamic_dynamic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_dynamic_dynamic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamic_dynamic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Object); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamic_dynamic_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectPaths); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamic_dynamic_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DynamicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamic_dynamic_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DynamicResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_dynamic_dynamic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dynamic_dynamic_proto_goTypes,
		DependencyIndexes: file_proto_dynamic_dynamic_proto_depIdxs,
		MessageInfos:      file_proto_dynamic_dynamic_proto_msgTypes,
	}.Build()
	File_proto_dynamic_dynamic_proto = out.File
	file_proto_dynamic_dynamic_proto_rawDesc = nil
	file_proto_dynamic_dynamic_proto_goTypes = nil
	file_proto_dynamic_dynamic_proto_depIdxs = nil
}
