syntax="proto3";

package proto;

option go_package = "github.com/Grow-Simplee-KGP/Thoth/proto";    

message Bin{
    int32 id=1;
    float length=2;
    float breadth=3;
    float height=4;
    float weight=5;
}

message Position{
    float x=1;
    float y=2;
    float z=3;
}

message BinPackingRequest{
    Bin bin=1;
    repeated Bin items=2;
}

message BinPackingResponse{
    repeated Bin items=1;
    repeated Position positions=2;
}

message Package{
    int32 id=1;
    float length=2;
    float breadth=3;
    float height=4;
    float weight=5;
    Location location=6;
}

message Location{
    float latitude=1;
    float longitude=2;
}

message Vehicle{    
    int32 id=1;
    Bin bag=2;
    float volume=3;
    float free_vol=4;
}

message CVRPRequest{
    int32 vehicle_count=1;
    int32 package_count=2;
    repeated Package packages=3;
    repeated Vehicle vehicles=4;
}

message Path{
    int32 vehicle_id=1;
    repeated int32 boxes=2;
}

message CVRPResponse{
    int32 vehicle_count=1;
    repeated Path path=2;
}

message SingleDynamicPath{
    repeated Package packages=1;
    Vehicle vehicle=2; 
}

message DynamicRequest{
    repeated SingleDynamicPath response=1;
}

service BinPacking{
    rpc RunBinPacking(BinPackingRequest) returns (BinPackingResponse){}    
}

service CVRP{
    rpc RunCVRP(CVRPRequest) returns (CVRPResponse){}
}
service DynamicRouting{
    rpc RunDynamix(DynamicRequest) returns (SingleDynamicPath){}
}