// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto/main.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TransportClient is the client API for Transport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransportClient interface {
	RunBinPacking(ctx context.Context, in *BinPackingRequest, opts ...grpc.CallOption) (*BinPackingResponse, error)
	RunCVRP(ctx context.Context, in *CVRPRequest, opts ...grpc.CallOption) (*CVRPResponse, error)
}

type transportClient struct {
	cc grpc.ClientConnInterface
}

func NewTransportClient(cc grpc.ClientConnInterface) TransportClient {
	return &transportClient{cc}
}

func (c *transportClient) RunBinPacking(ctx context.Context, in *BinPackingRequest, opts ...grpc.CallOption) (*BinPackingResponse, error) {
	out := new(BinPackingResponse)
	err := c.cc.Invoke(ctx, "/main.Transport/RunBinPacking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transportClient) RunCVRP(ctx context.Context, in *CVRPRequest, opts ...grpc.CallOption) (*CVRPResponse, error) {
	out := new(CVRPResponse)
	err := c.cc.Invoke(ctx, "/main.Transport/RunCVRP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransportServer is the server API for Transport service.
// All implementations must embed UnimplementedTransportServer
// for forward compatibility
type TransportServer interface {
	RunBinPacking(context.Context, *BinPackingRequest) (*BinPackingResponse, error)
	RunCVRP(context.Context, *CVRPRequest) (*CVRPResponse, error)
	mustEmbedUnimplementedTransportServer()
}

// UnimplementedTransportServer must be embedded to have forward compatible implementations.
type UnimplementedTransportServer struct {
}

func (UnimplementedTransportServer) RunBinPacking(context.Context, *BinPackingRequest) (*BinPackingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunBinPacking not implemented")
}
func (UnimplementedTransportServer) RunCVRP(context.Context, *CVRPRequest) (*CVRPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunCVRP not implemented")
}
func (UnimplementedTransportServer) mustEmbedUnimplementedTransportServer() {}

// UnsafeTransportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransportServer will
// result in compilation errors.
type UnsafeTransportServer interface {
	mustEmbedUnimplementedTransportServer()
}

func RegisterTransportServer(s grpc.ServiceRegistrar, srv TransportServer) {
	s.RegisterService(&Transport_ServiceDesc, srv)
}

func _Transport_RunBinPacking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BinPackingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransportServer).RunBinPacking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Transport/RunBinPacking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransportServer).RunBinPacking(ctx, req.(*BinPackingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transport_RunCVRP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CVRPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransportServer).RunCVRP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Transport/RunCVRP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransportServer).RunCVRP(ctx, req.(*CVRPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Transport_ServiceDesc is the grpc.ServiceDesc for Transport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Transport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.Transport",
	HandlerType: (*TransportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunBinPacking",
			Handler:    _Transport_RunBinPacking_Handler,
		},
		{
			MethodName: "RunCVRP",
			Handler:    _Transport_RunCVRP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/main.proto",
}
