// source: optimizer.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require("google-protobuf");
var goog = jspb;
var global = Function("return this")();

goog.exportSymbol("proto.optimizer.Bin", null, global);
goog.exportSymbol("proto.optimizer.Coordinate", null, global);
goog.exportSymbol("proto.optimizer.Dimension", null, global);
goog.exportSymbol("proto.optimizer.Item", null, global);
goog.exportSymbol("proto.optimizer.Position", null, global);
goog.exportSymbol("proto.optimizer.ServiceResponse", null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.optimizer.ServiceResponse = function (opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.optimizer.ServiceResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    proto.optimizer.ServiceResponse.displayName = "proto.optimizer.ServiceResponse";
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.optimizer.Dimension = function (opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.optimizer.Dimension, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    proto.optimizer.Dimension.displayName = "proto.optimizer.Dimension";
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.optimizer.Position = function (opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.optimizer.Position, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    proto.optimizer.Position.displayName = "proto.optimizer.Position";
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.optimizer.Coordinate = function (opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.optimizer.Coordinate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    proto.optimizer.Coordinate.displayName = "proto.optimizer.Coordinate";
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.optimizer.Item = function (opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.optimizer.Item, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    proto.optimizer.Item.displayName = "proto.optimizer.Item";
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.optimizer.Bin = function (opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.optimizer.Bin, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    proto.optimizer.Bin.displayName = "proto.optimizer.Bin";
}

if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.optimizer.ServiceResponse.prototype.toObject = function (opt_includeInstance) {
        return proto.optimizer.ServiceResponse.toObject(opt_includeInstance, this);
    };

    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.optimizer.ServiceResponse} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.optimizer.ServiceResponse.toObject = function (includeInstance, msg) {
        var f,
            obj = {};

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.optimizer.ServiceResponse}
 */
proto.optimizer.ServiceResponse.deserializeBinary = function (bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.optimizer.ServiceResponse();
    return proto.optimizer.ServiceResponse.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.optimizer.ServiceResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.optimizer.ServiceResponse}
 */
proto.optimizer.ServiceResponse.deserializeBinaryFromReader = function (msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.optimizer.ServiceResponse.prototype.serializeBinary = function () {
    var writer = new jspb.BinaryWriter();
    proto.optimizer.ServiceResponse.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.optimizer.ServiceResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.optimizer.ServiceResponse.serializeBinaryToWriter = function (message, writer) {
    var f = undefined;
};

if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.optimizer.Dimension.prototype.toObject = function (opt_includeInstance) {
        return proto.optimizer.Dimension.toObject(opt_includeInstance, this);
    };

    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.optimizer.Dimension} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.optimizer.Dimension.toObject = function (includeInstance, msg) {
        var f,
            obj = {
                length: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
                width: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
                height: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
            };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.optimizer.Dimension}
 */
proto.optimizer.Dimension.deserializeBinary = function (bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.optimizer.Dimension();
    return proto.optimizer.Dimension.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.optimizer.Dimension} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.optimizer.Dimension}
 */
proto.optimizer.Dimension.deserializeBinaryFromReader = function (msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = /** @type {number} */ (reader.readFloat());
                msg.setLength(value);
                break;
            case 2:
                var value = /** @type {number} */ (reader.readFloat());
                msg.setWidth(value);
                break;
            case 3:
                var value = /** @type {number} */ (reader.readFloat());
                msg.setHeight(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.optimizer.Dimension.prototype.serializeBinary = function () {
    var writer = new jspb.BinaryWriter();
    proto.optimizer.Dimension.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.optimizer.Dimension} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.optimizer.Dimension.serializeBinaryToWriter = function (message, writer) {
    var f = undefined;
    f = message.getLength();
    if (f !== 0.0) {
        writer.writeFloat(1, f);
    }
    f = message.getWidth();
    if (f !== 0.0) {
        writer.writeFloat(2, f);
    }
    f = message.getHeight();
    if (f !== 0.0) {
        writer.writeFloat(3, f);
    }
};

/**
 * optional float length = 1;
 * @return {number}
 */
proto.optimizer.Dimension.prototype.getLength = function () {
    return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};

/**
 * @param {number} value
 * @return {!proto.optimizer.Dimension} returns this
 */
proto.optimizer.Dimension.prototype.setLength = function (value) {
    return jspb.Message.setProto3FloatField(this, 1, value);
};

/**
 * optional float width = 2;
 * @return {number}
 */
proto.optimizer.Dimension.prototype.getWidth = function () {
    return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};

/**
 * @param {number} value
 * @return {!proto.optimizer.Dimension} returns this
 */
proto.optimizer.Dimension.prototype.setWidth = function (value) {
    return jspb.Message.setProto3FloatField(this, 2, value);
};

/**
 * optional float height = 3;
 * @return {number}
 */
proto.optimizer.Dimension.prototype.getHeight = function () {
    return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};

/**
 * @param {number} value
 * @return {!proto.optimizer.Dimension} returns this
 */
proto.optimizer.Dimension.prototype.setHeight = function (value) {
    return jspb.Message.setProto3FloatField(this, 3, value);
};

if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.optimizer.Position.prototype.toObject = function (opt_includeInstance) {
        return proto.optimizer.Position.toObject(opt_includeInstance, this);
    };

    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.optimizer.Position} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.optimizer.Position.toObject = function (includeInstance, msg) {
        var f,
            obj = {
                x: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
                y: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
                z: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
            };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.optimizer.Position}
 */
proto.optimizer.Position.deserializeBinary = function (bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.optimizer.Position();
    return proto.optimizer.Position.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.optimizer.Position} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.optimizer.Position}
 */
proto.optimizer.Position.deserializeBinaryFromReader = function (msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = /** @type {number} */ (reader.readFloat());
                msg.setX(value);
                break;
            case 2:
                var value = /** @type {number} */ (reader.readFloat());
                msg.setY(value);
                break;
            case 3:
                var value = /** @type {number} */ (reader.readFloat());
                msg.setZ(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.optimizer.Position.prototype.serializeBinary = function () {
    var writer = new jspb.BinaryWriter();
    proto.optimizer.Position.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.optimizer.Position} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.optimizer.Position.serializeBinaryToWriter = function (message, writer) {
    var f = undefined;
    f = message.getX();
    if (f !== 0.0) {
        writer.writeFloat(1, f);
    }
    f = message.getY();
    if (f !== 0.0) {
        writer.writeFloat(2, f);
    }
    f = message.getZ();
    if (f !== 0.0) {
        writer.writeFloat(3, f);
    }
};

/**
 * optional float x = 1;
 * @return {number}
 */
proto.optimizer.Position.prototype.getX = function () {
    return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};

/**
 * @param {number} value
 * @return {!proto.optimizer.Position} returns this
 */
proto.optimizer.Position.prototype.setX = function (value) {
    return jspb.Message.setProto3FloatField(this, 1, value);
};

/**
 * optional float y = 2;
 * @return {number}
 */
proto.optimizer.Position.prototype.getY = function () {
    return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};

/**
 * @param {number} value
 * @return {!proto.optimizer.Position} returns this
 */
proto.optimizer.Position.prototype.setY = function (value) {
    return jspb.Message.setProto3FloatField(this, 2, value);
};

/**
 * optional float z = 3;
 * @return {number}
 */
proto.optimizer.Position.prototype.getZ = function () {
    return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};

/**
 * @param {number} value
 * @return {!proto.optimizer.Position} returns this
 */
proto.optimizer.Position.prototype.setZ = function (value) {
    return jspb.Message.setProto3FloatField(this, 3, value);
};

if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.optimizer.Coordinate.prototype.toObject = function (opt_includeInstance) {
        return proto.optimizer.Coordinate.toObject(opt_includeInstance, this);
    };

    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.optimizer.Coordinate} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.optimizer.Coordinate.toObject = function (includeInstance, msg) {
        var f,
            obj = {
                longtitude: jspb.Message.getFieldWithDefault(msg, 1, 0),
                latitude: jspb.Message.getFieldWithDefault(msg, 2, 0),
            };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.optimizer.Coordinate}
 */
proto.optimizer.Coordinate.deserializeBinary = function (bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.optimizer.Coordinate();
    return proto.optimizer.Coordinate.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.optimizer.Coordinate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.optimizer.Coordinate}
 */
proto.optimizer.Coordinate.deserializeBinaryFromReader = function (msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = /** @type {number} */ (reader.readInt64());
                msg.setLongtitude(value);
                break;
            case 2:
                var value = /** @type {number} */ (reader.readInt64());
                msg.setLatitude(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.optimizer.Coordinate.prototype.serializeBinary = function () {
    var writer = new jspb.BinaryWriter();
    proto.optimizer.Coordinate.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.optimizer.Coordinate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.optimizer.Coordinate.serializeBinaryToWriter = function (message, writer) {
    var f = undefined;
    f = message.getLongtitude();
    if (f !== 0) {
        writer.writeInt64(1, f);
    }
    f = message.getLatitude();
    if (f !== 0) {
        writer.writeInt64(2, f);
    }
};

/**
 * optional int64 longtitude = 1;
 * @return {number}
 */
proto.optimizer.Coordinate.prototype.getLongtitude = function () {
    return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};

/**
 * @param {number} value
 * @return {!proto.optimizer.Coordinate} returns this
 */
proto.optimizer.Coordinate.prototype.setLongtitude = function (value) {
    return jspb.Message.setProto3IntField(this, 1, value);
};

/**
 * optional int64 latitude = 2;
 * @return {number}
 */
proto.optimizer.Coordinate.prototype.getLatitude = function () {
    return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};

/**
 * @param {number} value
 * @return {!proto.optimizer.Coordinate} returns this
 */
proto.optimizer.Coordinate.prototype.setLatitude = function (value) {
    return jspb.Message.setProto3IntField(this, 2, value);
};

if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.optimizer.Item.prototype.toObject = function (opt_includeInstance) {
        return proto.optimizer.Item.toObject(opt_includeInstance, this);
    };

    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.optimizer.Item} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.optimizer.Item.toObject = function (includeInstance, msg) {
        var f,
            obj = {
                id: jspb.Message.getFieldWithDefault(msg, 1, ""),
                size: (f = msg.getSize()) && proto.optimizer.Dimension.toObject(includeInstance, f),
                position: (f = msg.getPosition()) && proto.optimizer.Position.toObject(includeInstance, f),
                coordinates: (f = msg.getCoordinates()) && proto.optimizer.Coordinate.toObject(includeInstance, f),
                weight: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
                volume: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
            };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.optimizer.Item}
 */
proto.optimizer.Item.deserializeBinary = function (bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.optimizer.Item();
    return proto.optimizer.Item.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.optimizer.Item} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.optimizer.Item}
 */
proto.optimizer.Item.deserializeBinaryFromReader = function (msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = /** @type {string} */ (reader.readString());
                msg.setId(value);
                break;
            case 2:
                var value = new proto.optimizer.Dimension();
                reader.readMessage(value, proto.optimizer.Dimension.deserializeBinaryFromReader);
                msg.setSize(value);
                break;
            case 3:
                var value = new proto.optimizer.Position();
                reader.readMessage(value, proto.optimizer.Position.deserializeBinaryFromReader);
                msg.setPosition(value);
                break;
            case 4:
                var value = new proto.optimizer.Coordinate();
                reader.readMessage(value, proto.optimizer.Coordinate.deserializeBinaryFromReader);
                msg.setCoordinates(value);
                break;
            case 5:
                var value = /** @type {number} */ (reader.readFloat());
                msg.setWeight(value);
                break;
            case 6:
                var value = /** @type {number} */ (reader.readFloat());
                msg.setVolume(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.optimizer.Item.prototype.serializeBinary = function () {
    var writer = new jspb.BinaryWriter();
    proto.optimizer.Item.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.optimizer.Item} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.optimizer.Item.serializeBinaryToWriter = function (message, writer) {
    var f = undefined;
    f = message.getId();
    if (f.length > 0) {
        writer.writeString(1, f);
    }
    f = message.getSize();
    if (f != null) {
        writer.writeMessage(2, f, proto.optimizer.Dimension.serializeBinaryToWriter);
    }
    f = message.getPosition();
    if (f != null) {
        writer.writeMessage(3, f, proto.optimizer.Position.serializeBinaryToWriter);
    }
    f = message.getCoordinates();
    if (f != null) {
        writer.writeMessage(4, f, proto.optimizer.Coordinate.serializeBinaryToWriter);
    }
    f = message.getWeight();
    if (f !== 0.0) {
        writer.writeFloat(5, f);
    }
    f = message.getVolume();
    if (f !== 0.0) {
        writer.writeFloat(6, f);
    }
};

/**
 * optional string id = 1;
 * @return {string}
 */
proto.optimizer.Item.prototype.getId = function () {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};

/**
 * @param {string} value
 * @return {!proto.optimizer.Item} returns this
 */
proto.optimizer.Item.prototype.setId = function (value) {
    return jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * optional Dimension size = 2;
 * @return {?proto.optimizer.Dimension}
 */
proto.optimizer.Item.prototype.getSize = function () {
    return /** @type{?proto.optimizer.Dimension} */ (jspb.Message.getWrapperField(this, proto.optimizer.Dimension, 2));
};

/**
 * @param {?proto.optimizer.Dimension|undefined} value
 * @return {!proto.optimizer.Item} returns this
 */
proto.optimizer.Item.prototype.setSize = function (value) {
    return jspb.Message.setWrapperField(this, 2, value);
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.optimizer.Item} returns this
 */
proto.optimizer.Item.prototype.clearSize = function () {
    return this.setSize(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.optimizer.Item.prototype.hasSize = function () {
    return jspb.Message.getField(this, 2) != null;
};

/**
 * optional Position position = 3;
 * @return {?proto.optimizer.Position}
 */
proto.optimizer.Item.prototype.getPosition = function () {
    return /** @type{?proto.optimizer.Position} */ (jspb.Message.getWrapperField(this, proto.optimizer.Position, 3));
};

/**
 * @param {?proto.optimizer.Position|undefined} value
 * @return {!proto.optimizer.Item} returns this
 */
proto.optimizer.Item.prototype.setPosition = function (value) {
    return jspb.Message.setWrapperField(this, 3, value);
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.optimizer.Item} returns this
 */
proto.optimizer.Item.prototype.clearPosition = function () {
    return this.setPosition(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.optimizer.Item.prototype.hasPosition = function () {
    return jspb.Message.getField(this, 3) != null;
};

/**
 * optional Coordinate coordinates = 4;
 * @return {?proto.optimizer.Coordinate}
 */
proto.optimizer.Item.prototype.getCoordinates = function () {
    return /** @type{?proto.optimizer.Coordinate} */ (
        jspb.Message.getWrapperField(this, proto.optimizer.Coordinate, 4)
    );
};

/**
 * @param {?proto.optimizer.Coordinate|undefined} value
 * @return {!proto.optimizer.Item} returns this
 */
proto.optimizer.Item.prototype.setCoordinates = function (value) {
    return jspb.Message.setWrapperField(this, 4, value);
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.optimizer.Item} returns this
 */
proto.optimizer.Item.prototype.clearCoordinates = function () {
    return this.setCoordinates(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.optimizer.Item.prototype.hasCoordinates = function () {
    return jspb.Message.getField(this, 4) != null;
};

/**
 * optional float weight = 5;
 * @return {number}
 */
proto.optimizer.Item.prototype.getWeight = function () {
    return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};

/**
 * @param {number} value
 * @return {!proto.optimizer.Item} returns this
 */
proto.optimizer.Item.prototype.setWeight = function (value) {
    return jspb.Message.setProto3FloatField(this, 5, value);
};

/**
 * optional float volume = 6;
 * @return {number}
 */
proto.optimizer.Item.prototype.getVolume = function () {
    return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};

/**
 * @param {number} value
 * @return {!proto.optimizer.Item} returns this
 */
proto.optimizer.Item.prototype.setVolume = function (value) {
    return jspb.Message.setProto3FloatField(this, 6, value);
};

if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.optimizer.Bin.prototype.toObject = function (opt_includeInstance) {
        return proto.optimizer.Bin.toObject(opt_includeInstance, this);
    };

    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.optimizer.Bin} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.optimizer.Bin.toObject = function (includeInstance, msg) {
        var f,
            obj = {
                size: (f = msg.getSize()) && proto.optimizer.Dimension.toObject(includeInstance, f),
                capacity: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
            };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.optimizer.Bin}
 */
proto.optimizer.Bin.deserializeBinary = function (bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.optimizer.Bin();
    return proto.optimizer.Bin.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.optimizer.Bin} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.optimizer.Bin}
 */
proto.optimizer.Bin.deserializeBinaryFromReader = function (msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = new proto.optimizer.Dimension();
                reader.readMessage(value, proto.optimizer.Dimension.deserializeBinaryFromReader);
                msg.setSize(value);
                break;
            case 2:
                var value = /** @type {number} */ (reader.readFloat());
                msg.setCapacity(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.optimizer.Bin.prototype.serializeBinary = function () {
    var writer = new jspb.BinaryWriter();
    proto.optimizer.Bin.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.optimizer.Bin} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.optimizer.Bin.serializeBinaryToWriter = function (message, writer) {
    var f = undefined;
    f = message.getSize();
    if (f != null) {
        writer.writeMessage(1, f, proto.optimizer.Dimension.serializeBinaryToWriter);
    }
    f = message.getCapacity();
    if (f !== 0.0) {
        writer.writeFloat(2, f);
    }
};

/**
 * optional Dimension size = 1;
 * @return {?proto.optimizer.Dimension}
 */
proto.optimizer.Bin.prototype.getSize = function () {
    return /** @type{?proto.optimizer.Dimension} */ (jspb.Message.getWrapperField(this, proto.optimizer.Dimension, 1));
};

/**
 * @param {?proto.optimizer.Dimension|undefined} value
 * @return {!proto.optimizer.Bin} returns this
 */
proto.optimizer.Bin.prototype.setSize = function (value) {
    return jspb.Message.setWrapperField(this, 1, value);
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.optimizer.Bin} returns this
 */
proto.optimizer.Bin.prototype.clearSize = function () {
    return this.setSize(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.optimizer.Bin.prototype.hasSize = function () {
    return jspb.Message.getField(this, 1) != null;
};

/**
 * optional float capacity = 2;
 * @return {number}
 */
proto.optimizer.Bin.prototype.getCapacity = function () {
    return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};

/**
 * @param {number} value
 * @return {!proto.optimizer.Bin} returns this
 */
proto.optimizer.Bin.prototype.setCapacity = function (value) {
    return jspb.Message.setProto3FloatField(this, 2, value);
};

goog.object.extend(exports, proto.optimizer);
