// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto/clustering/clustering.proto

package clustering

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ClusteringClient is the client API for Clustering service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClusteringClient interface {
	GetClusters(ctx context.Context, in *ClusteringRequest, opts ...grpc.CallOption) (*ClusteringResponse, error)
}

type clusteringClient struct {
	cc grpc.ClientConnInterface
}

func NewClusteringClient(cc grpc.ClientConnInterface) ClusteringClient {
	return &clusteringClient{cc}
}

func (c *clusteringClient) GetClusters(ctx context.Context, in *ClusteringRequest, opts ...grpc.CallOption) (*ClusteringResponse, error) {
	out := new(ClusteringResponse)
	err := c.cc.Invoke(ctx, "/clustering.Clustering/GetClusters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusteringServer is the server API for Clustering service.
// All implementations must embed UnimplementedClusteringServer
// for forward compatibility
type ClusteringServer interface {
	GetClusters(context.Context, *ClusteringRequest) (*ClusteringResponse, error)
	mustEmbedUnimplementedClusteringServer()
}

// UnimplementedClusteringServer must be embedded to have forward compatible implementations.
type UnimplementedClusteringServer struct {
}

func (UnimplementedClusteringServer) GetClusters(context.Context, *ClusteringRequest) (*ClusteringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClusters not implemented")
}
func (UnimplementedClusteringServer) mustEmbedUnimplementedClusteringServer() {}

// UnsafeClusteringServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusteringServer will
// result in compilation errors.
type UnsafeClusteringServer interface {
	mustEmbedUnimplementedClusteringServer()
}

func RegisterClusteringServer(s grpc.ServiceRegistrar, srv ClusteringServer) {
	s.RegisterService(&Clustering_ServiceDesc, srv)
}

func _Clustering_GetClusters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusteringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusteringServer).GetClusters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clustering.Clustering/GetClusters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusteringServer).GetClusters(ctx, req.(*ClusteringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Clustering_ServiceDesc is the grpc.ServiceDesc for Clustering service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Clustering_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clustering.Clustering",
	HandlerType: (*ClusteringServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClusters",
			Handler:    _Clustering_GetClusters_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/clustering/clustering.proto",
}
